### ISSUE TITLE
[Android Roadmap needs to be converted into markdown format ] <readme.md file>

### ISSUE THREAD

**Issue by samvid2020** [commclassroom/roadmaps#222] opened 2022-10-16 18:04 UTC
### Description

The Android Roadmap should have its own readme.md file which it is precisely covering the content in markdown format without redirecting to the website!

**Comment by siddhant-khisty** [comment] 2022-10-17 11:46
Duplicate of #204

**Closed by siddhant-khisty** 2022-10-17 11:46 UTC
Labels: enhancement
